= Güvercin Yuvası Problemi

== Problem:

1 ile 200 arasında 101 tane sayı seçilmiş olsun. Bu sayılar arasında muhakkak öyle iki sayı vardır ki biri diğerini tam böler. Bunun ıspatının güvercin yucası prensibi ile yapılması


== Çözüm:

Öncelikle problemde istenildiği gibi 1 ile 200 arasında 101 tane rasgele sayı üretilip bir diziye aktarıldı. Bu işlemi yapan kaynak python kodları aşağıdaki gibidir.

[source,py]
----
import numpy as np
import random
sayilar = list(range(101))
#sayilar=[2,3,11,5,14]
for i in range(101):
    sayilar[i]=random.randint(1, 200)
print(sayilar)
----

Yukarıdaki kodlar çalıştırıldıktan sonra oluşturulan sayı dizisi aşağıdaki gibi oldu.

 [177, 32, 80, 89, 61, 23, 41, 174, 137, 99, 96, 36, 150, 132, 8, 165, 10, 37, 79, 113, 67, 119, 71, 3, 106, 153, 156, 180, 41, 82, 69, 20, 113, 9, 20, 84, 153, 10, 106, 50, 88, 152, 120, 176, 191, 162, 137, 14, 30, 103, 179, 163, 46, 80, 12, 93, 29, 74, 118, 7, 132, 124, 103, 165, 32, 123, 110, 173, 37, 92, 156, 96, 155, 74, 123, 7, 143, 14, 187, 169, 138, 41, 32, 148, 86, 20, 96, 193, 167, 41, 84, 75, 185, 27, 168, 6, 74, 171, 174, 41, 57]

Daha sonra bolen_sayisi değişkeni 0 değerine eşitlendi. Dizideki herbir değerin, geriye kalan diğerleriyle kalansız bölüp bölünmediği mod işlemiyle gerçekleştirildi. mod değeri 0 olduğunda bolen_sayisi değişkeni 1 arttırıldı.

Bir sayı kendini de kalansız bölüneceği için döngülerdeki i ve j değerleri eşit olmadığı sürece bu işlem gerçekleştirildi. Bu işlemler aşagıdaki gibi yapıldı.

[source,py]
----
bolen_sayisi=0
for i in range(101):
    for j in range(101):
        if i!=j:
            if sayilar[i] % sayilar[j]==0:
                bolen_sayisi+=1
----

En sonunda birbirini kalansız bölen sayı çifti adedi sayısı bulunup ekrana yazdırıldı.

[source,py]
----
print("Bu Sayı Dizisinde" , bolen_sayisi, "adet sayı çifti birbirini kalansız böler.") 
----

Yukarıdaki kodların çıktısı da aşağıdaki gibi oldu.

 Bu Sayı Dizisinde 275 adet sayı çifti birbirini kalansız böler.
 

Farklı bir sayı dizisindeki ekran çıktısı aşağıdaki gibidir. 

 [163, 19, 88, 168, 97, 15, 96, 171, 75, 169, 177, 37, 70, 165, 169, 75, 159, 194, 9, 107, 48, 12, 89, 63, 128, 52, 43, 140, 115, 27, 118, 150, 25, 124, 121, 46, 112, 27, 160, 155, 26, 55, 58, 50, 140, 49, 99, 56, 177, 164, 148, 166, 60, 176, 47, 53, 127, 44, 127, 117, 30, 42, 54, 120, 137, 152, 113, 99, 15, 154, 181, 165, 128, 10, 19, 125, 153, 34, 13, 64, 143, 55, 107, 12, 12, 157, 155, 14, 176, 5, 182, 187, 11, 138, 130, 78, 86, 47, 195, 97, 189]
 
 Bu Sayı Dizisinde 199 adet sayı çifti birbirini kalansız böler.


Kodların tamamı aşağıdadır.

pigeon2.py
[source,py]
----
import numpy as np
import random
sayilar = list(range(101))
#sayilar=[2,3,11,5,14]
for i in range(101):
    sayilar[i]=random.randint(1, 200)
print(sayilar)    
bolen_sayisi=0
for i in range(101):
    for j in range(101):
        if i!=j:
            if sayilar[i] % sayilar[j]==0:
                bolen_sayisi+=1
             
print("Bu Sayı Dizisinde" , bolen_sayisi, "adet sayı çifti birbirini kalansız böler.") 
----
